// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVzUu0mUkreSwfIrBHKrDvtwuq6W4XlHQ',
    appId: '1:687408117735:web:acc3a843d08c95dab8af42',
    messagingSenderId: '687408117735',
    projectId: 'lista-de-tarefas-1d25f',
    authDomain: 'lista-de-tarefas-1d25f.firebaseapp.com',
    storageBucket: 'lista-de-tarefas-1d25f.appspot.com',
    measurementId: 'G-QVEJJ7KESR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwhDhll6uA_yDKJoq_JcyeRoeBngVFr8w',
    appId: '1:687408117735:android:6bffb3df59d301adb8af42',
    messagingSenderId: '687408117735',
    projectId: 'lista-de-tarefas-1d25f',
    storageBucket: 'lista-de-tarefas-1d25f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzoNVaUU1bGlA-0E34DYGu449vMg38Q3U',
    appId: '1:687408117735:ios:e59c56d1e132cfb1b8af42',
    messagingSenderId: '687408117735',
    projectId: 'lista-de-tarefas-1d25f',
    storageBucket: 'lista-de-tarefas-1d25f.appspot.com',
    iosClientId: '687408117735-7ev250lrtshjjkeog0uu69echsc9mkbg.apps.googleusercontent.com',
    iosBundleId: 'com.example.listDeTarefasFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzoNVaUU1bGlA-0E34DYGu449vMg38Q3U',
    appId: '1:687408117735:ios:946f996775d82813b8af42',
    messagingSenderId: '687408117735',
    projectId: 'lista-de-tarefas-1d25f',
    storageBucket: 'lista-de-tarefas-1d25f.appspot.com',
    iosClientId: '687408117735-6poeeqrjvto9qudvus1tafv83fio0fip.apps.googleusercontent.com',
    iosBundleId: 'com.example.listDeTarefasFirebase.RunnerTests',
  );
}
